export { default as createReducer } from './createReducer' 
export { default as Container } from './Container'
export { default as Api } from './Api'
export { default as isIphoneX } from './isIphoneX'
export { default as SupportedBy } from './supportedby'